/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.41
 * Generated at: 2023-10-25 12:26:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("        <title>Tienda</title>\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css\">\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("        <header>\r\n");
      out.write("             <nav class=\"navbar fixed-top navbar-expand-lg navbar-dark  bg-dark bg-gradient\" style=\"min-height: 5vh;\">\r\n");
      out.write("                <a class=\"navbar-brand\" href=\"/Tienda\">Home</a>\r\n");
      out.write("                <button class=\"navbar-toggler\"  type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("                  <span class=\"navbar-toggler-icon\" ></span>\r\n");
      out.write("                </button>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("                  <ul class=\"navbar-nav mr-auto\">\r\n");
      out.write("                  </ul>\r\n");
      out.write("                  <form class=\"form-inline my-2 my-lg-0\">\r\n");
      out.write("                    <select class=\"form-control mr-sm-2\" name=\"categorias\" id=\"categoria\" placeholder=\"Filtrar Categoria...\">  \r\n");
      out.write("                        <option value=\"\">Seleccione Categoría</option>  \r\n");
      out.write("                        <option value=\"Carniceria\">Carnicería</option>  \r\n");
      out.write("                        <option value=\"Verduleria\">Verdulería</option>  \r\n");
      out.write("                        <option value=\"Panaderia\">Panadería</option>\r\n");
      out.write("                        <option value=\"Agua\">Agua</option>\r\n");
      out.write("                        <option value=\"Jugo\">Jugo</option>\r\n");
      out.write("                        <option value=\"Gaseosa\">Gaseosa</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                    <a class=\"btn btn-light\">Filtrar</a>\r\n");
      out.write("                  </form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </nav>\r\n");
      out.write("        </header>\r\n");
      out.write("        <div style=\"height: 5vh;\">\r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"has-bg-img z-index-1\">\r\n");
      out.write("            <div class=\"row-content\">\r\n");
      out.write("                <div class=\"col-sm-2\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-sm-8 mx-auto\">\r\n");
      out.write("                    <div class=\"text-center\" style=\"background-color:rgba(255, 255, 255, 0.9); position: absolute; width: 100%; margin-top: 10vh; margin-bottom: 10vh;\">\r\n");
      out.write("                        <h1>Seleccione la opción</h1>\r\n");
      out.write("                        <div class=\"row-content\" >\r\n");
      out.write("                            <div class=\"col-sm-6\">\r\n");
      out.write("                                <a href=\"agregarProd.jsp\" class=\"btn btn-dark\">Agregar Producto</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-sm-6\">\r\n");
      out.write("                                <a href=\"eliminarProd.jsp\" class=\"btn btn-dark\">Eliminar Producto</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"row-content\">\r\n");
      out.write("                            <div class=\"col-sm-6\">\r\n");
      out.write("                                <a href=\"buscarProd.jsp\" class=\"btn btn-dark\">Buscar Producto</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-sm-6\">\r\n");
      out.write("                                <a href=\"actualizarProd.jsp\" class=\"btn btn-dark\">Actualizar Stock</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"row-content\">\r\n");
      out.write("                            <div class=\"col-sm-6\">\r\n");
      out.write("                                <a href=\"agregarVenta.jsp\" class=\"btn btn-dark\">Vender</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-sm-6\">\r\n");
      out.write("                                <a href=\"verTotal.jsp\" class=\"btn btn-dark\">Ver Total de Ventas</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"row-content\">\r\n");
      out.write("                            <div class=\"col-sm-12\">\r\n");
      out.write("                                <form action=\"masVendido\" method=\"post\"><button class=\"btn btn-dark\">\r\n");
      out.write("                            Producto Más Vendido\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </form>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-sm-2\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("\r\n");
      out.write("            <img class=\"bg obj-fit-cover img-fluid\" src=\"tienda2.jpg\" style=\"width: 100%\">   \r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <footer class=\"bg-dark text-white\">\r\n");
      out.write("            <p>Hola</p>\r\n");
      out.write("        </footer>\r\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/jquery@3.6.4/dist/jquery.slim.min.js\"></script>\r\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
